name: Doxygen

on:
  schedule:
    - cron: '10 3 * * 1'
      # Mondays at 03:10
  workflow_dispatch:

jobs:
  doxygen:
    name: Update Code Docs
    runs-on: ubuntu-latest
    container: debian:sid

    steps:
    - name: Check Secret
      run: |
        [ -n "${{ secrets.DOXYGEN_DEPLOY_KEY }}" ]

    - name: Install Build Software
      run: |
        apt-get update
        apt install -y doxygen graphviz git rsync

    - name: Set Up Git
      run: |
        git config --global user.email "rich@flatcap.org"
        git config --global user.name "Richard Russon (DEPLOY)"

    - name: Checkout NeoMutt
      uses: actions/checkout@v3.3.0
      with:
        repository: neomutt/neomutt
        path: neomutt
        fetch-depth: 0

    - name: Checkout Doxygen Scripts
      uses: actions/checkout@v3.3.0
      with:
        repository: neomutt/action-doxygen
        path: action-doxygen

    - name: Checkout Code Docs
      uses: actions/checkout@v3.3.0
      with:
        repository: neomutt/code
        path: code
        persist-credentials: false
        # otherwise GITHUB_TOKEN will be used, rather than the Personal Access Token

    - name: Generate Docs
      run: |
        cd neomutt
        ln -s ../action-doxygen
        action-doxygen/bin/generate.sh
        ls -l html/index.html

    - name: Commit Docs
      run: |
        action-doxygen/bin/commit.sh neomutt/html code

    - name: Push to Code Docs
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.DOXYGEN_DEPLOY_KEY }}
        branch: main
        directory: code
        repository: neomutt/code

